serviceAccount:
  create: true
  name: fluent-bit

config:
  filters: |
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log On
        K8S-Logging.Exclude On
        K8S-Logging.Parser On

    [FILTER]
        Name   parser
        Match  *
        Key_Name log
        Parser  json
        Reserve_Data On

    [FILTER]
        Name   modify
        Match  *
        Remove stream
        Remove _p
        Remove time

  #   [FILTER]
  #       Name           kubernetes
  #       Match          kube.nginx-ingress.*
  #       Kube_URL       https://kubernetes.default.svc:443
  #       Merge_Log      On
  #       K8S-Logging.Exclude On
  #       K8S-Logging.Parser On

  outputs: |
    [OUTPUT]
        name loki
        match *
        host loki.monitoring.svc.cluster.local
        port 3100
        labels level=$level,job=fluent-bit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],app=$kubernetes['labels']['app.kubernetes.io/name']
        line_format json
        log_level info
        remove_keys kubernetes

resources:
  requests:
    cpu: 100m
    memory: 128Mi