serviceAccount:
  create: true
  name: fluent-bit

config:
  inputs: |
    [INPUT]
        Name  tail
        Path  /var/log/containers/*.log
        Tag   kube.*
        multiline.parser docker, cri
        Exclude_Path  *nginx*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name  tail
        Path  /var/log/containers/*nginx*.log
        Tag   nginx.*
        multiline.parser docker, cri
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On


    [INPUT]
        Name  systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On


  filters: |
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log      On
        K8S-Logging.Exclude On
        K8S-Logging.Parser On

    [FILTER]
        Name           kubernetes
        Match          nginx.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log      On
        K8S-Logging.Exclude On
        K8S-Logging.Parser On

    # Only parse logs that start with '{' (likely JSON)
    [FILTER]
        Name   grep
        Match  *
        Regex  log ^\{

    [FILTER]
        Name   parser
        Match  *
        Key_Name log
        Parser  json
        Reserve_Data On

    [FILTER]
        Name   modify
        Match  *
        Remove stream
        Remove _p
        Remove time

  outputs: |
    [OUTPUT]
        name loki
        match kube.*
        host loki.monitoring.svc.cluster.local
        port 3100
        labels level=$level,job=fluent-bit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],app=$kubernetes['labels']['app.kubernetes.io/name']
        line_format json
        log_level info
        remove_keys kubernetes

    [OUTPUT]
        name loki
        match nginx.*
        host loki.monitoring.svc.cluster.local
        port 3100
        labels cluster=devops
        line_format json
        log_level info
        # remove_keys kubernetes

resources:
  requests:
    cpu: 100m
    memory: 128Mi