{{- if .Values.initJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-credentials-sync-init
  namespace: argocd
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ecr-credentials-sync
      volumes:
        - emptyDir:
            medium: Memory
          name: token
      initContainers:
        - image: amazon/aws-cli
          name: get-token
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ce
            - aws ecr get-login-password --region {{ .Values.region }} > /token/ecr-token
          volumeMounts:
            - mountPath: /token
              name: token
      containers:
        - name: create-secret
          image: bitnami/kubectl
          imagePullPolicy: IfNotPresent
          command: ["/script/ecr-credentials.sh"]
          volumeMounts:
            - name: script
              mountPath: "/script"
            - mountPath: /token
              name: token
      volumes:
        - name: script
          configMap:
            name: ecr-credentials-configmap
            defaultMode: 0770
        - emptyDir:
            medium: Memory
          name: token
{{- end }} 