apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credentials-sync
  namespace: argocd
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: ecr-credentials-sync
          volumes:
            - name: token
              emptyDir:
                medium: Memory
            - name: script
              configMap:
                name: ecr-credentials-configmap
                defaultMode: 0770
          initContainers:
            - image: amazon/aws-cli
              name: get-token
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -ce
                - aws ecr get-login-password --region {{ .Values.region }} > /token/ecr-token
              volumeMounts:
                - mountPath: /token
                  name: token
          containers:
            - name: create-secret
              image: bitnami/kubectl
              imagePullPolicy: IfNotPresent
              command: ["/script/ecr-credentials.sh"]
              volumeMounts:
                - name: script
                  mountPath: "/script"
                - mountPath: /token
                  name: token