apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: data-node
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  amiFamily: AL2
  amiSelectorTerms:
    - id: {{ .Values.dataNode.ami }}
  role: {{ .Values.nodeClass.role }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        iops: 10000
        encrypted: true
        deleteOnTermination: true
        throughput: 125
        kmsKeyID: {{ .Values.dataNode.kmsKeyId }}
        snapshotID: snap-095d39f453364a8fa
        volumeInitializationRate: 100
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.nodeClass.discovery }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.nodeClass.discovery }}
  tags:
    app: data-node
    Name: karpenter-data-node
    Environment: {{ .Values.environment }}