apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: system-tools
  source:
    repoURL: https://github.com/kubernetes/autoscaler.git
    targetRevision: cluster-autoscaler-chart-9.37.0
    path: charts/cluster-autoscaler
    helm:
      values: |
        extraArgs:
          scale-down-delay-after-add: 30s
          scale-down-unneeded-time: 10m
        awsRegion: {{ .Values.awsRegion }}
        autoDiscovery:
          clusterName: {{ .Values.clusterName }}
        rbac:
          create: true
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: {{ .Values.clusterAutoscaler.roleArn }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true