apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: system-tools
  source:
    repoURL: "https://github.com/vmware-tanzu/helm-charts.git"
    targetRevision: velero-7.2.1
    path: charts/velero
    helm:
      values: |
        initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.10.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
        configuration:
          backupStorageLocation:
            - name: "s3"
              provider: "aws"
              default: true
              bucket: "{{ .Values.velero.bucketID }}"
              accessMode: "ReadWrite"
              config: {
                region: "{{ .Values.awsRegion }}"
              }
          volumeSnapshotLocation:
            - name: "aws"
              provider: "aws"
              config: {
                region: {{ .Values.awsRegion }}
              }
        podAnnotations: {
          eks.amazonaws.com/role-arn: "{{ .Values.velero.roleArn }}"
        }
        defaultBackupStorageLocation: "s3"
        credentials:
          useSecret: false
        serviceAccount:
          server:
            name: "velero"
            annotations:
              eks.amazonaws.com/role-arn: "{{ .Values.velero.roleArn }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true