apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-credentials-configmap
data:
  ecr-credentials.sh: |
    #!/bin/bash
    kubectl -n argocd create secret docker-registry ecr-credentials \
      --dry-run=client \
      --docker-server="{{ .Values.ECR_REGISTRY }}" \
      --docker-username=AWS \
      --docker-password="$(</token/ecr-token)" \
      -o yaml | kubectl apply -f - && \
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-ecr-helm-credentials
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      username: AWS
      password: $(</token/ecr-token)
      enableOCI: "true"
      name: "ECR"
      type: "helm"
      url: "{{ .Values.ECR_REGISTRY }}"
    EOF